export const categoryConstants={
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILED:'GET_ALL_CATEGORIES_FAILED',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILED:'ADD_NEW_CATEGORY_FAILED'
}

export const productConstants={
    GET_ALL_PRODUCTS_BY_SLUG_REQUEST:'GET_ALL_PRODUCTS_BY_SLUG_REQUEST',
    GET_ALL_PRODUCTS_BY_SLUG_SUCCESS:'GET_ALL_PRODUCTS_BY_SLUG_SUCCESS',
    GET_ALL_PRODUCTS_BY_SLUG_FAILED:'GET_ALL_PRODUCTS_BY_SLUG_FAILED',
    GET_PRODUCT_DETAILS_BY_ID_REQUEST:'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS:'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILED:'GET_PRODUCT_DETAILS_BY_ID_FAILED',
    GET_PRODUCT_PAGE_REQUEST:'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS:'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILED:'GET_PRODUCT_PAGE_FAILED'
}

export const authConstants={
    SIGNUP_REQUEST:'SIGNUP_REQUEST',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_FAILED:'SIGNUP_FAILED',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED'
}

export const cartConstants={
    ADD_TO_CART:'ADD_TO_CART',
    RESET_CART:'RESET_CART'
}

export const userConstants={
    GET_USER_ADDRESS_REQUEST:'GET_USER_ADDRESS_REQUEST',
    GET_USER_ADDRESS_SUCCESS:'GET_USER_ADDRESS_SUCCESS',
    GET_USER_ADDRESS_FAILED:'GET_USER_ADDRESS_FAILED',
    ADD_USER_ADDRESS_REQUEST:'ADD_USER_ADDRESS_REQUEST',
    ADD_USER_ADDRESS_SUCCESS:'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILED:'ADD_USER_ADDRESS_FAILED',
    ADD_USER_ORDER_REQUEST:'ADD_USER_ORDER_REQUEST',
    ADD_USER_ORDER_SUCCESS:'ADD_USER_ORDER_SUCCESS',
    ADD_USER_ORDER_FAILED:'ADD_USER_ORDER_FAILED',
    GET_USER_ORDERS_REQUEST:'GET_USER_ORDERS_REQUEST',
    GET_USER_ORDERS_SUCCESS:'GET_USER_ORDERS_SUCCESS',
    GET_USER_ORDERS_FAILED:'GET_USER_ORDERS_FAILED'
}

export const productModalConstants={
    GET_PRODUCT_MODAL_SUCCESS:'GET_PRODUCT_MODAL_SUCCESS',
    ADD_PRODUCT_MODAL_SUCCESS:'ADD_PRODUCT_MODAL_SUCCESS',
    REMOVE_PRODUCT_MODAL:'REMOVE_PRODUCT_MODAL'
}
